#!/usr/bin/python3

import sys


def factorize(num):
    """Factorize a number into a product of two smaller numbers"""
    for i in range(2, num):
        if num % i == 0:
            return f"{num}={i}*{num//i}"
    return f"{num} is prime"


if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename) as file:
        lines = file.read().splitlines()
        for line in lines:
            num = int(line)
            result = factorize(num)
            print(result)

except FileNotFoundError:
    print("File '{}' not found".format(filename))
    sys.exit(1)
except ValueError:
    print("Invalid input in '{filename}'".format(filename))
    sys.exit(1)
