#!/usr/bin/python3

import sys
import math


def factorize(num):
    """Factorize a number into a product of two smaller numbers"""
    if num % 2 == 0:
        return ("{}=2*{}".format(num, num // 2))
    for i in range(3, int(math.sqrt(num)) + 1, 2):
        if num % i == 0:
            return ("{}={}*{}".fomart(num, i, num // i))
    return ("{} is prime".format(num))


if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename) as file:
        lines = file.read().splitlines()
        for line in lines:
            num = int(line)
            result = factorize(num)
            print(result)

except FileNotFoundError:
    print("File '{}' not found".format(filename))
    sys.exit(1)
except ValueError:
    print("Invalid input in '{}'".format(filename))
    sys.exit(1)
